---
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  push:
    branches: [devel, main]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - run: >
          dnf install --refresh -y
          cmake
          createrepo_c-devel
          gcc-c++
          git
          gtest-devel
          libassuan-devel
          make
          valgrind
      - uses: actions/checkout@v2
      - run: mkdir -p build
      - run: >
          cmake ..
          -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          "-DCMAKE_C_FLAGS=-Werror"
          "-DMEMORYCHECK_COMMAND_OPTIONS=-q --tool=memcheck --leak-check=yes
          --error-exitcode=1 --gen-suppressions=all"
        working-directory: ${{github.workspace}}/build
      - run: cmake --build . -j2
        working-directory: ${{github.workspace}}/build
      - run: >
          ctest
          --output-on-failure
          -j2
          -D ExperimentalMemCheck
        working-directory: ${{github.workspace}}/build
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: MemoryChecker
          if-no-files-found: ignore
          path: |
            ${{github.workspace}}/build/Testing/Temporary/MemoryChecker.*.log
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yamllint .
